"""Top-level Firestore collections whose records are explicitly owner scoped."""

OWNER_DATA_COLLECTIONS = (
    "conversations",
    "messages",
    "conversation_summaries",
    "research_sessions",
    "research_request_keys",
    "itinerary_proposals",
    "booking_document_extractions",
    "iterative_research_runs",
    "iterative_research_request_keys",
    "memories",
    "derived_memories",
    "derived_memory_sources",
    "memory_lifecycle_states",
    "memory_lifecycle_events",
    "memory_lifecycle_jobs",
    "memory_lifecycle_operations",
    "canonical_entities",
    "entity_aliases",
    "entity_claims",
    "entity_matches",
    "decision_snapshots",
    "decision_evidence_snapshots",
    "candidate_evaluations",
    "domain_registrations",
    "domain_claim_extensions",
    "provider_observations",
    "domain_comparison_views",
    "domain_lookup_idempotency",
    "audit_events",
)
