"""Application domain entities."""

from personal_ai.entities.conversation import (
    MAX_MESSAGE_CONTENT_CHARS,
    Conversation,
    Message,
    MessageRole,
    MessageStatus,
)
from personal_ai.entities.research import (
    AvailabilityValue,
    BooleanValue,
    CanonicalEntity,
    DateTimeValue,
    DateValue,
    DateWindowValue,
    EntityAlias,
    EntityClaim,
    EntityMatch,
    EvidenceEntityLink,
    EvidenceReference,
    LocationValue,
    MoneyValue,
    NumberValue,
    QuantityValue,
    TextValue,
)

__all__ = [
    "MAX_MESSAGE_CONTENT_CHARS",
    "AvailabilityValue",
    "BooleanValue",
    "CanonicalEntity",
    "Conversation",
    "DateTimeValue",
    "DateValue",
    "DateWindowValue",
    "EntityAlias",
    "EntityClaim",
    "EntityMatch",
    "EvidenceEntityLink",
    "EvidenceReference",
    "LocationValue",
    "Message",
    "MessageRole",
    "MessageStatus",
    "MoneyValue",
    "NumberValue",
    "QuantityValue",
    "TextValue",
]
